"""create_pricelist_rules_and_promo_codes

Revision ID: e72535a982c1
Revises: 014_create_orders_table
Create Date: 2026-08-09 06:55:39.776262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72535a982c1'
down_revision: Union[str, Sequence[str], None] = '014_create_orders_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    insp = sa.inspect(conn)
    existing_tables = insp.get_table_names()

    if 'monthly_store_targets' not in existing_tables:
        op.create_table('monthly_store_targets',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('target_value', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id')
        )
        op.create_index(op.f('ix_monthly_store_targets_id'), 'monthly_store_targets', ['id'], unique=False)

    if 'promo_codes' not in existing_tables:
        op.create_table('promo_codes',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('vendor_id', sa.Integer(), nullable=False),
            sa.Column('code', sa.String(length=50), nullable=False),
            sa.Column('discount_percent', sa.Float(), nullable=False),
            sa.Column('max_uses', sa.Integer(), nullable=False),
            sa.Column('uses_count', sa.Integer(), nullable=False),
            sa.Column('start_date', sa.String(length=50), nullable=False),
            sa.Column('end_date', sa.String(length=50), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_promo_codes_id'), 'promo_codes', ['id'], unique=False)
    else:
        promo_cols = [c['name'] for c in insp.get_columns('promo_codes')]
        if 'uses_count' not in promo_cols:
            op.add_column('promo_codes', sa.Column('uses_count', sa.Integer(), nullable=False, server_default='0'))

    if 'pricelist_rules' not in existing_tables:
        op.create_table('pricelist_rules',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('vendor_id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=120), nullable=False),
            sa.Column('discount_percent', sa.Float(), nullable=False),
            sa.Column('start_date', sa.String(length=50), nullable=False),
            sa.Column('end_date', sa.String(length=50), nullable=False),
            sa.Column('is_global', sa.Boolean(), nullable=False),
            sa.Column('product_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_pricelist_rules_id'), 'pricelist_rules', ['id'], unique=False)

    try:
        op.alter_column('products', 'sales_price',
                   existing_type=sa.FLOAT(),
                   nullable=True,
                   existing_server_default=sa.text("'0.0'"))
        op.alter_column('products', 'cost_price',
                   existing_type=sa.FLOAT(),
                   nullable=True,
                   existing_server_default=sa.text("'0.0'"))
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'cost_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0.0'"))
    op.alter_column('products', 'sales_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0.0'"))
    op.drop_index(op.f('ix_pricelist_rules_id'), table_name='pricelist_rules')
    op.drop_table('pricelist_rules')
    op.drop_index(op.f('ix_promo_codes_id'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_monthly_store_targets_id'), table_name='monthly_store_targets')
    op.drop_table('monthly_store_targets')
    # ### end Alembic commands ###
